# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import chunkdemo_pb2 as chunkdemo__pb2


class ChunkDemoStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.DownloadArray = channel.unary_stream(
        '/chunkdemo.ChunkDemo/DownloadArray',
        request_serializer=chunkdemo__pb2.StreamRequest.SerializeToString,
        response_deserializer=chunkdemo__pb2.Chunk.FromString,
        )


class ChunkDemoServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def DownloadArray(self, request, context):
    """Send a series of chunks containing an array
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_ChunkDemoServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'DownloadArray': grpc.unary_stream_rpc_method_handler(
          servicer.DownloadArray,
          request_deserializer=chunkdemo__pb2.StreamRequest.FromString,
          response_serializer=chunkdemo__pb2.Chunk.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'chunkdemo.ChunkDemo', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
